name: Deploy the Subgraph

on:
  workflow_dispatch:
    inputs:
      graph_environment:
        description: The Graph environment to deploy to
        required: true
        default: 'graph-studio-devnet'
        type: choice
        options:
          - graph-studio-devnet
          - graph-studio-testnet
          - graph-studio-mainnet
      subgraph:
        description: The name of the subgraph to deploy
        required: true
        default: 'core'
        type: choice
        options:
          - core
          - drt
      update:
        description: Whether to update the subgraph with the current artifacts for the selected network.
        required: true
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.graph_environment }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Validate Network environment variable
        if:   ${{!startsWith(vars.NETWORK, 'arbitrum')}}
        run:  echo ${{vars.NETWORK}} && exit 1

      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 20

      - name: Install Yarn if running locally
        if: ${{ env.ACT }}
        run: npm install -g yarn

      - name: Install the dependencies
        run: yarn install

      - name: Install jq and yq
        if: ${{ inputs.update }}  
        run: |
          mkdir bin
          wget -qO bin/jq https://github.com/jqlang/jq/releases/download/jq-1.6/jq-linux64
          wget -qO bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x bin/jq bin/yq 

      - name: Update the subgraph definition
        if: ${{ inputs.update }}
        run: |
          export PATH=$PWD/../bin:$PATH
          yarn update:${{ inputs.subgraph }}:${{ vars.NETWORK }}
        working-directory: subgraph

      - name: Build the subgraph
        run: |
          yarn codegen:${{ inputs.subgraph }}
          yarn build:${{ inputs.subgraph }}
        working-directory: subgraph
        
      - name: Authenticate with TheGraph Studio
        run: yarn graph auth "${{ secrets.SUBGRAPH_AUTH_TOKEN }}" --studio
        working-directory: subgraph

      - name: Deploy the subgraph
        run: |
          # working around a graph bug which doesn't exit 1 on error: https://github.com/graphprotocol/graph-tooling/issues/1570
          error=$(yarn deploy:${{ inputs.subgraph }}:${{ vars.NETWORK }})
          echo "$error"
          if [[ $error == *"Error"* ]]
          then
            echo "exiting..."
            exit 1 
          else
            echo "deployed successfully"
            exit 0
          fi
        working-directory: subgraph
